version: "3.6"
services:
  api:
    build: .
    ports:
      - 4000:4000
    environment:
      NODE_ENV: development
      DB_HOST: db
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - ./scripts/pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: nodejs
      POSTGRES_MULTIPLE_DATABASES: spendesk,spendesk_test
